var x;
var userName = "manikanta";
console.log("hello how are " + userName);
var collection = ["manikanta", "teja", "yuva"];
console.log("hi all how are ".concat(collection[0]));
var collection1 = ["manikanta", 101, 55.06, "teja"];
console.log(collection1);
var collection3 = new Array("mani", "teja");
var collection4 = new Array();
collection4[0] = "manikanta";
collection4[1] = 101;
collection4[2] = "yuva";
console.log(collection4);
